### ISSUE TITLE
Documentation about adding javaagent to Maven Surefire Plugin is not complete

### ISSUE THREAD

**Issue by maksymgendin** [tginsberg/junit5-system-exit#18]
In order to get the new 2.0.0 version to work with Maven and the `${com.ginsberg:junit5-system-exit:jar}` property in `argLine` of `maven-surefire-plugin` I had to add following execution to `maven-dependency-plugin`:

```xml
<plugin>
    <artifactId>maven-dependency-plugin</artifactId>
    <executions>
        <execution>
            <goals>
                <goal>properties</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

Would be great if you could extend the docs. Many thanks!

**Comment by tginsberg** [comment]
Thanks @maksymgendin! I had this in my test application harness (which I should probably check in as well) but neglected to include it in the documentation. I appreciate you catching this and providing the correct syntax!
