### ISSUE TITLE
How to test multiple exits 

### ISSUE THREAD

**Issue by edayan** [tginsberg/junit5-system-exit#20]
Maybe it is easy, but I am struggling with the following scenario.

```
public void multipleExit() {
		try {
			// .. some logic
			System.exit(0);
		} catch (Exception e) {
			System.out.println("Exiting with 10");
			System.exit(10);
		}
	}

```

how to test wheather the application exited with code '0'?

**Comment by tginsberg** [comment]
Hi @edayan 

Most of the instructions should be on the README for this project, but a loose outline is:

1. Add the dependency to your build.
2. Add the Java Agent to your test runner (see README for both Gradle and Maven examples)
3. Pick one way to do the tests, either the JUnit5 Extension, or fluid assertions.

Assuming you do all that, the easiest way is probably with the fluid assertions method:


```java
public class MyTestClasses {
    
    @Test
    void thatSystemExitIsCalled() {
        assertThatCallsSystemExit(() -> 
                // Code that calls System.exit() here
        ).withExitCode(0);
    }
}
```

**Comment by edayan** [comment]
Hi @tginsberg,

Thank you for the quick response. I realize I didn't fully explain the issue I'm encountering. Here's the scenario:

```
@Test
	public void testSysTest() {
		assertThatCallsSystemExit(() -> {
			try {
				// .. some logic
				System.exit(0);
			} catch (Exception e) {
				System.exit(10);
			}
		}).withExitCode(0);
	}


```

This test always fails because the actual result is exit code 10. However, I need to validate that the situation produces an exit code of 0, not 10.

**Comment by tginsberg** [comment]
Cool, thanks for the update. I see why this is happening, there is a bug in the exit handler:

```java
public static void handleExit(final int status) {
    if(isRunningTest) {
        if (firstExitStatusCode == null) {
            firstExitStatusCode = status;
        }
        throw new SystemExitPreventedException(status);
    } else {
        System.exit(status);
    }
}
```

That line `throw SystemExitPreventedException(status)` should always be `firstExitStatusCode`, or else you get the condition you've highlighted.

I'll fix this and issue a new release, probably 2.0.1

**Comment by tginsberg** [comment]
Fixed and released. It might take a couple of hours for version 2.0.1 to show up in Maven Central. 

Thanks for the report @edayan!

**Comment by edayan** [comment]
@tginsberg 
I have noticed another behavior, when we have multiple tests in the same class

```
public class ExitTest {

	@Test
	public void firstTest() {
		assertThatCallsSystemExit(() -> {
			try {
				System.exit(10);
			} catch (Exception e) {
				System.exit(20);
			}
		}).withExitCode(10);
	}

	@Test
	public void secondTest() {
		assertThatCallsSystemExit(() -> {
			try {
				System.exit(0);
			} catch (Exception e) {
				System.exit(20);
			}
		}).withExitCode(0);
	}
}
```

The secondTest fails with Actual result from firstTest. Is it because `resetBetweenTests` is not called here?

**Comment by tginsberg** [comment]
Bah, you're probably right. I don't have time tonight, but I'll fix this over the weekend and push another new version, probably 2.0.2. Thanks again for the report and sticking with this.

**Comment by tginsberg** [comment]
Will handle in #24
