### ISSUE TITLE
NoSystemExit annotation

### ISSUE THREAD

**Issue by eric-unc** [tginsberg/junit5-system-exit#4]
Maybe there's a way to do this but it would be cool if there was an annotation that allowed a test method to call system exit without breaking all of the tests, but just failing that specific test.

For now I'm using `@ExpectSystemExitWithStatus(-1)` and putting `System.exit(-1);` at the end, so if a different `System.exit` happens the test will fail.

**Comment by tginsberg** [comment]
Could you give me a small example of what you mean? I'm able to annotate multiple tests with `@ExpectSystemExit` and `@ExpectSystemExitWithStatus` and they all run independently. So I think I probably just don't understand your use case.

**Comment by eric-unc** [comment]
Sorry if I was unclear. These tests are all good and well. I want a test that fails _if_ there is a system exit.

Tests will fail per default if there is, but it halts the whole JUnit process and doesn't produce a report.

**Comment by tginsberg** [comment]
Ah, gotcha. Yeah, that is a good use case. Sort of the opposite of `@ExpectSystemExit` then, something like `@FailOnSystemExit` (with perhaps a better name). 

Thanks for taking the time to fill out a request and respond! I'll see what I can do!

**Comment by eric-unc** [comment]
Indeed, it would be the exact opposite 😛 `@FailOnSystemExit` is a decent name (definitely better than my idea of `@NoSystemExit`).

**Comment by tginsberg** [comment]
This has been done in release 1.1.0, which should now be in Maven Central. Thanks for the suggestion!

**Comment by eric-unc** [comment]
Seems to be working for static methods but not non-static methods? So this works:
![image](https://user-images.githubusercontent.com/54514192/108620652-888f2480-73fb-11eb-9bd8-51234f1763cf.png)
But not this:
![image](https://user-images.githubusercontent.com/54514192/108620656-9644aa00-73fb-11eb-9fbd-69b7015a71d4.png)
Is that to be expected? I don't know much about JUnit but seems weird it works in one case but not the other.

**Comment by tginsberg** [comment]
Yeah, I missed something in my testing. Let me see if I can get this today. Sorry, that's a bug on me.

**Comment by tginsberg** [comment]
Fixed in 1.1.1 - Thanks for being patient, and sorry this slipped through. I was testing the wrong things.

BTW - I don't think JUnit5 supports [static methods annotated with `@Test`](https://junit.org/junit5/docs/current/user-guide/#writing-tests-classes-and-methods):

> Test Method: any instance method that is directly annotated or meta-annotated with `@Test`, `@RepeatedTest`, `@ParameterizedTest`, `@TestFactory`, or `@TestTemplate`.

**Comment by eric-unc** [comment]
Seems to be working now, thanks! (the non-static method)
